name: Release Drafter Cloudflare KV
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - main
    paths:
      - "cloudflarekv/**"
jobs:
  draft_release_cloudflarekv:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-cloudflarekv.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
