on:
    push:
        branches:
            - master
            - main
        paths:
            - 'mssql/**'
    pull_request:
        paths:
            - 'mssql/**'
name: "Tests MSSQL"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                env:
                    TEST_MSSQL_IMAGE: "mcr.microsoft.com/mssql/server:2022-RTM-GDR1-ubuntu-20.04"
                run: cd ./mssql && go test ./... -v -race
