on:
  push:
    branches:
      - master
      - main
    paths:
      - 'clickhouse/**'
  pull_request:
    paths:
      - 'clickhouse/**'
name: 'Tests Clickhouse'
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.21.x
          - 1.22.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Startup Clickhouse
        run: |
          docker run -d -p 9001:9000 --name clickhouse --ulimit nofile=262144:262144 clickhouse/clickhouse-server
          sleep 30
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Test
        run: cd ./clickhouse && go clean -testcache && go test ./... -v -race
