on:
    push:
        branches:
            - master
            - main
        paths:
            - 'minio/**'
    pull_request:
        paths:
            - 'minio/**'
name: "Tests Minio"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
            -   name: Install MinIO
                run: |
                    docker run -d --restart always -p 9000:9000 --name storage-minio -e MINIO_ROOT_USER='minio-user' -e MINIO_ROOT_PASSWORD='minio-password' minio/minio server /data

            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                run: cd ./minio && go test ./... -v -race
